name: Github Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run |
         echo " job was triggerd by event: ${{ github.event_name }}"
         echo " nmae of the branch is ${{ github.ref }} and your repo is ."

    - uses: actions/checkout@v3.3.0

    -name: List files in the repo
      run: |
        echo "The repo ${{ githbu.repository }} contains following files:"
        tree
    
    
